"""
Agent Schemas
=============

Pydantic models for standardized agent input/output and status tracking.
"""

from __future__ import annotations

import enum
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


# ------------------------------------------------------------------
# Enums
# ------------------------------------------------------------------

class AgentStatus(str, enum.Enum):
    """Lifecycle status of an agent."""

    IDLE = "idle"
    INITIALIZING = "initializing"
    PROCESSING = "processing"
    ERROR = "error"


class Severity(str, enum.Enum):
    """Severity level for flagged items."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# ------------------------------------------------------------------
# Input / Output
# ------------------------------------------------------------------

class AgentInput(BaseModel):
    """Standardized input payload sent to any agent."""

    request_id: UUID = Field(default_factory=uuid4)
    session_id: Optional[UUID] = None
    payload: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class TranscriptSegment(BaseModel):
    """A single transcript segment with optional speaker and timing."""

    text: str
    start: Optional[float] = None
    end: Optional[float] = None
    speaker: Optional[str] = None
    confidence: Optional[float] = None


class ToneSegment(BaseModel):
    """Tone or confidence information extracted from speech."""

    speaker: Optional[str] = None
    confidence: Optional[float] = None
    sentiment: Optional[float] = None
    energy: Optional[float] = None
    notes: Optional[str] = None


class KPIExtraction(BaseModel):
    """A KPI or metric extracted from a slide."""

    label: str
    value: Optional[str] = None
    context: Optional[str] = None
    confidence: Optional[float] = None


class SlideInsight(BaseModel):
    """A structured view of a single slide's analysis."""

    slide_index: Optional[int] = None
    title: Optional[str] = None
    summary: Optional[str] = None
    kpis: List[KPIExtraction] = Field(default_factory=list)
    guidance: List[str] = Field(default_factory=list)


class VerificationResult(BaseModel):
    """A claim-level verification result against filings."""

    claim: str
    status: str
    evidence: Optional[str] = None
    confidence: Optional[float] = None


class HistoricalComparison(BaseModel):
    """Quarter-over-quarter or year-over-year comparison context."""

    metric: Optional[str] = None
    current: Optional[float] = None
    previous: Optional[float] = None
    delta: Optional[float] = None
    notes: List[str] = Field(default_factory=list)


class IntelligenceReport(BaseModel):
    """Structured output generated by the orchestrator."""

    executive_summary: str = ""
    tone_analysis: Dict[str, Any] = Field(default_factory=dict)
    consistency_score: float = 0.0
    risk_factors: List[Dict[str, Any]] = Field(default_factory=list)
    slide_speech_comparison: List[Dict[str, Any]] = Field(default_factory=list)
    historical_comparison: Dict[str, Any] = Field(default_factory=dict)
    full_report: str = ""
    verification_results: List[Dict[str, Any]] = Field(default_factory=list)


class FlaggedItem(BaseModel):
    """A single flagged insight, risk, or anomaly."""

    label: str
    description: str
    severity: Severity = Severity.LOW
    evidence: Optional[str] = None


class AgentOutput(BaseModel):
    """Standardized output returned by any agent."""

    request_id: UUID
    agent_name: str
    success: bool = True
    data: Dict[str, Any] = Field(default_factory=dict)
    flags: List[FlaggedItem] = Field(default_factory=list)
    errors: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    completed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
